name: app_secomp
description: Aplicativo Mobile para a X Semana da Computação da UFSCar

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  gradient_app_bar: ^0.0.1
  android_intent: ^0.3.0
  loading: ^1.0.1
  provider: ^3.0.0
  flutter_spinkit: ^ 3.1.0
  progress_indicators: ^ 0.1.2
  webview_flutter:  ^0.3.9
  url_launcher: ^5.0.5
  bloc_pattern: ^2.2.3
  rxdart: ^0.22.0
  google_maps_flutter: ^0.4.0
  carousel_slider: ^1.3.0
  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.12.9+1
  shared_preferences: ^0.5.3
  dio: 2.1.16
  dio_http_cache: ^0.1.3 
  pull_to_refresh: ^1.5.4


dev_dependencies:

  flutter_test:
    sdk: flutter
  
  connectivity: ^0.3.0
  cached_network_image: ^1.1.1
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato/Lato-HairlineItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Lato/Lato-Hairline.ttf
          weight: 100
        - asset: fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Lato/Lato-Black.ttf
          weight: 900
    - family:  SecompSocial
      fonts:
        - asset: fonts/SecompSocial.ttf
